pay1193/Pay1193/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Mvc;
using Pay1193.Services;
using Pay1193.Entity;
using Pay1193.Models;

namespace Pay1193.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly IEmployee _employeeService;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public EmployeeController(IEmployee employeeService, IWebHostEnvironment webHostEnvironment)
        {
            _employeeService = employeeService;
            _webHostEnvironment = webHostEnvironment;
        }

        public IActionResult Index()
        {
            var employee = _employeeService.GetAll().Select(employee => new EmployeeIndexViewModel
            {
                Id = employee.Id,
                EmployeeNo = employee.EmployeeNo,
                FullName = employee.FullName,
                Gender = employee.Gender,
                ImageUrl = employee.ImageUrl,
                DateJoined = employee.DateJoined,
                Designation = employee.Designation,
                City = employee.City
            }).ToList();
            return View(employee);
        }

        public IActionResult Detail(int id)
        {
            var employee = _employeeService.GetById(id);
            if(employee == null)
            {
                return NotFound();
            }
            EmployeeDetailsViewModel model = new EmployeeDetailsViewModel()
            {
                Id = employee.Id,
                EmployeeNo = employee.EmployeeNo,
                FullName = employee.FullName,
                Gender = employee.Gender,
                ImageUrl = employee.ImageUrl,
                DoB = employee.DoB,
                Designation = employee.Designation,
                Email = employee.Email,
                NationalInsuranceNo = employee.NationalInsuranceNo,
                PaymentMethod = employee.PaymentMethod,
                StudentLoan = employee.StudentLoan,
                UnionMember = employee.UnionMember,
                Address = employee.Address,
                City = employee.City,
                PostCode = employee.PostCode
            };
            return View(model);
        }
        [HttpGet]
        public IActionResult Create()
        {
            var model = new EmployeeCreateViewModel();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(EmployeeCreateViewModel model)
        {
            if (ModelState.IsValid)
            {
                var employee = new Employee
                {
                    Id = model.Id,
                    FirstName = model.FirstName,
                    MiddleName = model.MidleName,
                    LatName = model.LastName,
                    Gender = model.Gender,
                    DoB = model.DOB,
                    DateJoined = model.DateJoined,
                    Designation = model.Designation,
                    NationalInsuranceNo = model.NationalInsuranceNo,
                    StudentLoan = model.StudentLoan,
                    PaymentMethod = model.PaymentMethod,
                    UnionMember= model.UnionMember,
                    Phone = model.Phone,
                    Address = model.Address,
                    City = model.City,
                    PostCode = model.Postcode,
                    Email = model.Email,
                    EmployeeNo = model.EmployeeNo,
                    FullName = model.FullName
                };
                if(model.ImageUrl != null & model.ImageUrl.Length > 0)
                {
                    var uploadDir = @"images/employees";
                    var filename = Path.GetFileNameWithoutExtension(model.ImageUrl.FileName);
                    var extension = Path.GetExtension(model.ImageUrl.FileName);
                    var webrootPath = _webHostEnvironment.WebRootPath;
                    filename = DateTime.UtcNow.ToString("yymmssfff") + filename + extension;
                    var path = Path.Combine(webrootPath,uploadDir, filename);
                    await model.ImageUrl.CopyToAsync(new FileStream(path, FileMode.Create));
                    employee.ImageUrl = "/" + uploadDir + "/" + filename;

                }
                await _employeeService.CreateAsync(employee);
                return RedirectToAction("Index");
            }
            return View(); 
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var employee = _employeeService.GetById(id);
            if(employee == null)
            {
                return NotFound();
            }
            var model = new EmployeeEditViewModel()
            {
                Id = employee.Id,
                FirstName = employee.FirstName,
                LastName = employee.LatName,
                MidleName = employee.MiddleName,
                EmployeeNo = employee.EmployeeNo,
                Gender = employee.Gender,
                Email = employee.Email,
                DOB = employee.DoB,
                DateJoined = employee.DateJoined,
                Designation = employee.Designation,
                NationalInsuranceNo = employee.NationalInsuranceNo,
                PaymentMethod = employee.PaymentMethod,
                StudentLoan = employee.StudentLoan,
                UnionMember = employee.UnionMember,
                Address = employee.Address,
                City = employee.City,
                Postcode = employee.PostCode
            };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EmployeeEditViewModel model)
        {
            if (ModelState.IsValid)
            {
                var employee = new Employee
                {
                    Id = model.Id,
                    FirstName = model.FirstName,
                    MiddleName = model.MidleName,
                    LatName = model.LastName,
                    Gender = model.Gender,
                    DoB = model.DOB,
                    DateJoined = model.DateJoined,
                    Designation = model.Designation,
                    NationalInsuranceNo = model.NationalInsuranceNo,
                    StudentLoan = model.StudentLoan,
                    PaymentMethod = model.PaymentMethod,
                    UnionMember = model.UnionMember,
                    Phone = model.Phone,
                    Address = model.Address,
                    City = model.City,
                    PostCode = model.Postcode,
                    Email = model.Email,
                    EmployeeNo = model.EmployeeNo,
                    FullName = model.FullName
                };
                if (model.ImageUrl != null & model.ImageUrl.Length > 0)
                {
                    var uploadDir = @"images/employees";
                    var filename = Path.GetFileNameWithoutExtension(model.ImageUrl.FileName);
                    var extension = Path.GetExtension(model.ImageUrl.FileName);
                    var webrootPath = _webHostEnvironment.WebRootPath;
                    filename = DateTime.UtcNow.ToString("yymmssfff") + filename + extension;
                    var path = Path.Combine(webrootPath, uploadDir, filename);
                    await model.ImageUrl.CopyToAsync(new FileStream(path, FileMode.Create));
                    employee.ImageUrl = "/" + uploadDir + "/" + filename;

                }
                await _employeeService.UpdateAsync(employee);
                return RedirectToAction("Index");
            }
            return View();
        }
        [HttpGet]
        public IActionResult Delete(int id)
        {
            var employee = _employeeService.GetById(id);
            if(employee == null)
            {
                return NotFound();
            }
            var model = new EmployeeDeleteViewModel
            {
                Id = employee.Id,
                FullName = employee.FullName
            };
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Delete(EmployeeDeleteViewModel model)
        {
            await _employeeService.Delete(model.Id);
            return RedirectToAction("Index");
        }
    }
}

pay1193/Pay1193/Views/Employee/Create.cshtml
@model EmployeeCreateViewModel

<div class="col-md-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a asp-controller="Employee" asp-action="Index">Employee List</a>
                    </li>
                    <li class="breadcrumb-item active" aria-current="page">New Employee</li>
                </ol>
            </nav><br />
            <form method="post" asp-action="Create" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-row">
                    <div class="form-group col-md-2">
                        <label asp-for="EmployeeNo"></label>
                    </div>
                    <div class="form-group col-md-3">
                        <input type="text" class="form-control" asp-for="EmployeeNo" placeholder="EMP000" />
                        <span asp-validation-for="EmployeeNo" class="text-danger"></span>
                    </div>

                    <div class="col-md-2">
                    </div>

                    <div class="form-group col-md-2">
                        <label asp-for="DateJoined"></label>
                    </div>
                    <div class="form-group col-md-3">
                        <input type="date" class="form-control" asp-for="DateJoined" />
                        <span asp-validation-for="DateJoined" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-2">
                        <label asp-for="FirstName"></label>
                    </div>
                    <div class="form-group col-md-3">
                        <input type="text" class="form-control" asp-for="FirstName" placeholder="Enter First Name" />
                        <span asp-validation-for="FirstName" class="text-danger"></span>
                    </div>

                    <div class="form-group col-md-2">
                        <input type="text" class="form-control" asp-for="MidleName" placeholder="Enter Middle Name" />
                        <span asp-validation-for="MidleName" class="text-danger"></span>
                    </div>

                    <div class="form-group col-md-2">
                        <label asp-for="LastName"></label>
                    </div>
                    <div class="form-group col-md-3">
                        <input type="text" class="form-control" asp-for="LastName" />
                        <span asp-validation-for="LastName" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-2">
                        <label asp-for="Gender"></label>
                    </div>
                    <div class="form-group col-md-3">
                        <select asp-for="Gender" class="form-control">
                            <option>Male</option>
                            <option>Female</option>
                        </select>
                        <span asp-validation-for="EmployeeNo" class="text-danger"></span>
                    </div>

                    <div class="col-md-2">
                    </div>

                    <div class="form-group col-md-2">
                        <label asp-for="DOB"></label>
                    </div>
                    <div class="form-group col-md-3">
                        <input type="date" class="form-control" asp-for="DOB" />
                        <span asp-validation-for="DOB" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-2">
                        <label asp-for="NationalInsuranceNo"></label>
                    </div>
                    <div class="form-group col-md-3">
                        <input type="text" class="form-control" asp-for="NationalInsuranceNo" placeholder="Enter NI Number" />
                        <span asp-validation-for="NationalInsuranceNo" class="text-danger"></span>
                    </div>

                    <div class="col-md-2">
                    </div>

                    <div class="form-group col-md-2">
                        <label asp-for="Email"></label>
                    </div>
                    <div class="form-group col-md-3">
                        <input type="email" class="form-control" asp-for="Email" placeholder="Enter Email" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-2">
                        <label asp-for="Phone"></label>
                    </div>
                    <div class="form-group col-md-3">
                        <input type="text" class="form-control" asp-for="Phone" placeholder="Enter Phone Number" />
                        <span asp-validation-for="Phone" class="text-danger"></span>
                    </div>

                    <div class="col-md-2">
                    </div>

                    <div class="form-group col-md-2">
                        <label asp-for="PaymentMethod"></label>
                    </div>
                    <div class="form-group col-md-3">
                        <select asp-for="PaymentMethod" class="form-control" asp-items="Html.GetEnumSelectList<PaymentMethod>()"></select>
                        <span asp-validation-for="PaymentMethod" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-2">
                        <label asp-for="StudentLoan"></label>
                    </div>
                    <div class="form-group col-md-3">
                        <select asp-for="StudentLoan" class="form-control" asp-items="Html.GetEnumSelectList<StudentLoan>()"></select>
                        <span asp-validation-for="StudentLoan" class="text-danger"></span>
                    </div>

                    <div class="col-md-2">
                    </div>

                    <div class="form-group col-md-2">
                        <label asp-for="UnionMember"></label>
                    </div>
                    <div class="form-group col-md-3">
                        <select asp-for="UnionMember" class="form-control" asp-items="Html.GetEnumSelectList<UnionMember>()"></select>
                        <span asp-validation-for="UnionMember" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-2">
                        <label asp-for="Designation"></label>
                    </div>
                    <div class="form-group col-md-3">
                        <input type="text" class="form-control" asp-for="Designation" placeholder="Enter Role" />
                        <span asp-validation-for="Designation" class="text-danger"></span>
                    </div>

                    <div class="col-md-2"></div>

                    <div class="form-group col-md-1">
                        <label asp-for="ImageUrl"></label>
                    </div>
                    <div class="form-group col-md-4">
                        <div class="btn btn-primary btn-icon-text">
                            <i class="fas fa-cloud-upload-alt"></i>
                            <input type="file" value="Upload" asp-for="ImageUrl" />
                            <span asp-validation-for="ImageUrl" class="text-danger"></span>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="Address"></label>
                    <input asp-for="Address" class="form-control" placeholder="Enter Address" />
                    <span asp-validation-for="Address" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="City"></label>
                    <input asp-for="City" class="form-control" placeholder="Enter City" />
                    <span asp-validation-for="City" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Postcode"></label>
                    <input asp-for="Postcode" class="form-control" placeholder="Enter Post Code" />
                    <span asp-validation-for="Postcode" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <button type="submit" class="btn btn-secondary btn-rounded float-left" style="margin-right:auto.7em">Submit</button>
                    <a asp-controller="Employee" asp-action="Index" class="btn btn-primary btn-rounded float-right" style="margin-right:auto.7em">Cancel</a>
                    <br />
                    <br />
                </div>

            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_validationScriptsPartial");
    }
}

pay1193/Pay1193/Views/Employee/Delete.cshtml
@model EmployeeDeleteViewModel

<div class="col-md-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a asp-controller="Employee" asp-action="Index">Employee List</a>
                    </li>
                    <li class="breadcrumb-item active" aria-current="page">Delete Employee</li>
                </ol>
            </nav><br />
            <form method="post" asp-action="Delete" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <input asp-for="FullName" class="form-control font-weight-bold" readonly style="background-color: #293043"/>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-secondary btn-rounded float-left"><i class="fas fa-plus-square" style="margin-right:auto.7em"></i>Delete</button>
                    <a asp-controller="Employee" asp-action="Index" class="btn btn-primary btn-rounded float-right" ><i class="fas fa-caret-square-left" style="margin-right:auto.7em"></i>Cancel</a>
                    <br />
                    <br />
                </div>

            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_validationScriptsPartial");
    }
    }

pay1193/Pay1193/Views/Employee/Detail.cshtml
@model EmployeeDetailsViewModel

<div class="col-md-12 grid-margin grid-margin-md-0">
    <div class="card">
        <div class="card-body">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a asp-controller="Employee" asp-action="Index">Employee List</a>
                    </li>
                    <li class="breadcrumb-item active" aria-current="page">Employee Detail</li>
                </ol>
            </nav><br />
            <div class="wrap d-flex justify-content-start justify-content-sm-center flex-wrap">
                <img class="rounded-circle shadow-lg" style="width:300px; height:350px" src="@Url.Content(Model.ImageUrl)"/>
                <div class="wrap align-items-center ml-5">
                    <p class="font-weight-bold text-success" style="font-size20px">@Model.FullName</p>
                    <p class="font-weight-bold text-success">Role: @Model.Designation</p>
                    <p class="font-weight-bold text-success">Gender: @Model.Gender</p>
                    <p class="font-weight-bold text-success">Date Of Birth: @Model.DoB.ToString("dd/MM/yyyy")</p>
                    <p class="font-weight-bold text-success">Employee Number: @Model.EmployeeNo</p>
                    <p class="font-weight-bold text-success">NI Number: @Model.NationalInsuranceNo</p>
                    <p class="font-weight-bold text-success">Email: @Model.Email</p>
                    <br /><br />
                    <p class="font-weight-bold">Pay & Deduction</p>
                    <hr style="background-color:crimson"/>
                    <p class="font-weight-normal text-success">Payment Method: @Model.PaymentMethod</p>
                    <p class="font-weight-normal text-success">Student Loan: @Model.StudentLoan</p>
                    <p class="font-weight-normal text-success">Union Member: @Model.UnionMember</p>
                    <br /><br />
                    <p class="font-weight-bold">Address</p>
                    <hr style="background-color:crimson" />
                    <p class="font-weight-normal">@Model.Address</p>
                    <p class="font-weight-normal">@Model.City</p>
                    <p class="font-weight-normal">@Model.PostCode</p>
                </div>
            </div>
        </div>
    </div>
</div>

pay1193/Pay1193/Views/Employee/Edit.cshtml
@model EmployeeEditViewModel

<div class="col-md-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a asp-controller="Employee" asp-action="Index">Employee List</a>
                    </li>
                    <li class="breadcrumb-item active" aria-current="page">Edit Employee</li>
                </ol>
            </nav><br />
            <form method="post" asp-action="Create" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-row">
                    <div class="form-group col-md-2">
                        <label asp-for="EmployeeNo"></label>
                    </div>
                    <div class="form-group col-md-3">
                        <input type="text" class="form-control" asp-for="EmployeeNo" placeholder="EMP000" />
                        <span asp-validation-for="EmployeeNo" class="text-danger"></span>
                    </div>

                    <div class="col-md-2">
                    </div>

                    <div class="form-group col-md-2">
                        <label asp-for="DateJoined"></label>
                    </div>
                    <div class="form-group col-md-3">
                        <input type="date" class="form-control" asp-for="DateJoined" />
                        <span asp-validation-for="DateJoined" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-2">
                        <label asp-for="FirstName"></label>
                    </div>
                    <div class="form-group col-md-3">
                        <input type="text" class="form-control" asp-for="FirstName" placeholder="Enter First Name" />
                        <span asp-validation-for="FirstName" class="text-danger"></span>
                    </div>

                    <div class="form-group col-md-2">
                        <input type="text" class="form-control" asp-for="MidleName" placeholder="Enter Middle Name" />
                        <span asp-validation-for="MidleName" class="text-danger"></span>
                    </div>

                    <div class="form-group col-md-2">
                        <label asp-for="LastName"></label>
                    </div>
                    <div class="form-group col-md-3">
                        <input type="text" class="form-control" asp-for="LastName" />
                        <span asp-validation-for="LastName" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-2">
                        <label asp-for="Gender"></label>
                    </div>
                    <div class="form-group col-md-3">
                        <select asp-for="Gender" class="form-control">
                            <option>Male</option>
                            <option>Female</option>
                        </select>
                        <span asp-validation-for="EmployeeNo" class="text-danger"></span>
                    </div>

                    <div class="col-md-2">
                    </div>

                    <div class="form-group col-md-2">
                        <label asp-for="DOB"></label>
                    </div>
                    <div class="form-group col-md-3">
                        <input type="date" class="form-control" asp-for="DOB" />
                        <span asp-validation-for="DOB" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-2">
                        <label asp-for="NationalInsuranceNo"></label>
                    </div>
                    <div class="form-group col-md-3">
                        <input type="text" class="form-control" asp-for="NationalInsuranceNo" placeholder="Enter NI Number" />
                        <span asp-validation-for="NationalInsuranceNo" class="text-danger"></span>
                    </div>

                    <div class="col-md-2">
                    </div>

                    <div class="form-group col-md-2">
                        <label asp-for="Email"></label>
                    </div>
                    <div class="form-group col-md-3">
                        <input type="email" class="form-control" asp-for="Email" placeholder="Enter Email" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-2">
                        <label asp-for="Phone"></label>
                    </div>
                    <div class="form-group col-md-3">
                        <input type="text" class="form-control" asp-for="Phone" placeholder="Enter Phone Number" />
                        <span asp-validation-for="Phone" class="text-danger"></span>
                    </div>

                    <div class="col-md-2">
                    </div>

                    <div class="form-group col-md-2">
                        <label asp-for="PaymentMethod"></label>
                    </div>
                    <div class="form-group col-md-3">
                        <select asp-for="PaymentMethod" class="form-control" asp-items="Html.GetEnumSelectList<PaymentMethod>()"></select>
                        <span asp-validation-for="PaymentMethod" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-2">
                        <label asp-for="StudentLoan"></label>
                    </div>
                    <div class="form-group col-md-3">
                        <select asp-for="StudentLoan" class="form-control" asp-items="Html.GetEnumSelectList<StudentLoan>()"></select>
                        <span asp-validation-for="StudentLoan" class="text-danger"></span>
                    </div>

                    <div class="col-md-2">
                    </div>

                    <div class="form-group col-md-2">
                        <label asp-for="UnionMember"></label>
                    </div>
                    <div class="form-group col-md-3">
                        <select asp-for="UnionMember" class="form-control" asp-items="Html.GetEnumSelectList<UnionMember>()"></select>
                        <span asp-validation-for="UnionMember" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-2">
                        <label asp-for="Designation"></label>
                    </div>
                    <div class="form-group col-md-3">
                        <input type="text" class="form-control" asp-for="Designation" placeholder="Enter Role" />
                        <span asp-validation-for="Designation" class="text-danger"></span>
                    </div>

                    <div class="col-md-2"></div>

                    <div class="form-group col-md-1">
                        <label asp-for="ImageUrl"></label>
                    </div>
                    <div class="form-group col-md-4">
                        <div class="btn btn-primary btn-icon-text">
                            <i class="fas fa-cloud-upload-alt"></i>
                            <input type="file" value="Upload" asp-for="ImageUrl" />
                            <span asp-validation-for="ImageUrl" class="text-danger"></span>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="Address"></label>
                    <input asp-for="Address" class="form-control" placeholder="Enter Address" />
                    <span asp-validation-for="Address" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="City"></label>
                    <input asp-for="City" class="form-control" placeholder="Enter City" />
                    <span asp-validation-for="City" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Postcode"></label>
                    <input asp-for="Postcode" class="form-control" placeholder="Enter Post Code" />
                    <span asp-validation-for="Postcode" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <button type="submit" class="btn btn-secondary btn-rounded float-left" style="margin-right:auto.7em">Save</button>
                    <a asp-controller="Employee" asp-action="Index" class="btn btn-primary btn-rounded float-right" style="margin-right:auto.7em">Cancel</a>
                    <br />
                    <br />
                </div>

            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_validationScriptsPartial");
    }
}