pay1193/Pay1193/Models/PaymentRecordViewModel.cs
namespace Pay1193.Models
{
    public class PaymentRecordDeleteViewModel
    {
        public int Id { get; set; }
        public string FullName { get; set; }
    }
}

pay1193/Pay1193/Controllers/PaymentRecordController.cs
using Microsoft.AspNetCore.Mvc;
using Pay1193.Services;
using Pay1193.Entity;
using Pay1193.Models;
using System.Dynamic;

namespace Pay1193.Controllers
{
    public class PaymentRecordController : Controller
    {
        private readonly IPaymentRecord _paymentRecordService;
        private readonly IEmployee _employeeService;
        private readonly ITaxService _taxService;
        private readonly INationalInsuranceService _nationalInsuranceService;
        private readonly IPayService _payService;

        //private decimal overtimeHrs;
        //private decimal contractualEarnings;
        //private decimal overtimeEarnings;
        //private decimal totalEarnings;
        //private decimal tax;
        //private decimal unionFee;
        //private decimal studentLoan;
        //private decimal nationalInsurance;
        //private decimal totalDeduction;

        public PaymentRecordController(IPaymentRecord paymentRecordService, IEmployee employeeService, ITaxService taxService, INationalInsuranceService nationalInsuranceService, IPayService payService)
        {
            _paymentRecordService = paymentRecordService;
            _employeeService = employeeService;
            _taxService = taxService;
            _nationalInsuranceService = nationalInsuranceService;
            _payService = payService;
        }

        public IActionResult Index()
        {
            var paymentRecords = _paymentRecordService.GetAll().Select(paymentRecordItem => new PaymentRecordIndexViewModel
            {
                FullName = _employeeService.GetById(paymentRecordItem.EmployeeId).FullName,
                DatePay = paymentRecordItem.DatePay,
                MonthPay = paymentRecordItem.MonthPay,
                TaxYearId = paymentRecordItem.TaxYearId,
                TaxYear = _taxService.GetById(paymentRecordItem.TaxYearId).YearOfTax,
                TotalEarnings = paymentRecordItem.TotalEarnings,
                EarningDeduction = paymentRecordItem.EarningDeduction,
                NetPayment = paymentRecordItem.NetPayment,
            }).ToList();

            return View(paymentRecords);
        }


        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.employees = _employeeService.GetAll();
            ViewBag.taxYears = _paymentRecordService.GetAllTaxYear();
            var model = new PaymentRecordCreateViewModel();
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(PaymentRecordCreateViewModel model)
        {
            //if (ModelState.IsValid)
            //{
            var paymentRecord = new PaymentRecord
            { 
                EmployeeId = model.EmployeeId,
                Employee = _employeeService.GetById(model.EmployeeId),
                DatePay = model.DatePay,
                MonthPay = model.MonthPay,
                TaxYearId = model.TaxYearId,
                TaxYear = _taxService.GetById(model.TaxYearId),
                HourlyRate = model.HourlyRate,
                HourWorked = model.HourWorked,
                ContractualHours = model.ContractualHours,
                ContractualEarnings = _payService.ContractualEarning(model.ContractualHours, model.HourWorked, model.HourlyRate),

                TaxCode = ""
            };


            await _paymentRecordService.CreateAsync(paymentRecord);
            return RedirectToAction("Index");
            //}
            //return View();
        }

        //public IActionResult Detail(int id)
        //{
        //    var PaymentRecord = _PaymentRecordService.GetById(id);
        //    if (PaymentRecord == null)
        //    {
        //        return NotFound();
        //    }
        //    PaymentRecordDetailsViewModel model = new PaymentRecordDetailsViewModel()
        //    {
        //        Id = PaymentRecord.Id,
        //        PaymentRecordNo = PaymentRecord.PaymentRecordNo,
        //        FullName = PaymentRecord.FullName,
        //        Gender = PaymentRecord.Gender,
        //        ImageUrl = PaymentRecord.ImageUrl,
        //        DoB = PaymentRecord.DoB,
        //        Designation = PaymentRecord.Designation,
        //        Email = PaymentRecord.Email,
        //        NationalInsuranceNo = PaymentRecord.NationalInsuranceNo,
        //        PaymentMethod = PaymentRecord.PaymentMethod,
        //        StudentLoan = PaymentRecord.StudentLoan,
        //        UnionMember = PaymentRecord.UnionMember,
        //        Address = PaymentRecord.Address,
        //        City = PaymentRecord.City,
        //        PostCode = PaymentRecord.PostCode
        //    };
        //    return View(model);
        //}

        //[HttpGet]
        //public IActionResult Edit(int id)
        //{
        //    var PaymentRecord = _PaymentRecordService.GetById(id);
        //    if (PaymentRecord == null)
        //    {
        //        return NotFound();
        //    }
        //    var model = new PaymentRecordEditViewModel()
        //    {
        //        Id = PaymentRecord.Id,
        //        FirstName = PaymentRecord.FirstName,
        //        LastName = PaymentRecord.LatName,
        //        MidleName = PaymentRecord.MiddleName,
        //        PaymentRecordNo = PaymentRecord.PaymentRecordNo,
        //        Gender = PaymentRecord.Gender,
        //        Email = PaymentRecord.Email,
        //        DOB = PaymentRecord.DoB,
        //        DateJoined = PaymentRecord.DateJoined,
        //        Designation = PaymentRecord.Designation,
        //        NationalInsuranceNo = PaymentRecord.NationalInsuranceNo,
        //        PaymentMethod = PaymentRecord.PaymentMethod,
        //        StudentLoan = PaymentRecord.StudentLoan,
        //        UnionMember = PaymentRecord.UnionMember,
        //        Address = PaymentRecord.Address,
        //        City = PaymentRecord.City,
        //        Postcode = PaymentRecord.PostCode
        //    };
        //    return View(model);
        //}

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Edit(PaymentRecordEditViewModel model)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        var PaymentRecord = new PaymentRecord
        //        {
        //            Id = model.Id,
        //            FirstName = model.FirstName,
        //            MiddleName = model.MidleName,
        //            LatName = model.LastName,
        //            Gender = model.Gender,
        //            DoB = model.DOB,
        //            DateJoined = model.DateJoined,
        //            Designation = model.Designation,
        //            NationalInsuranceNo = model.NationalInsuranceNo,
        //            StudentLoan = model.StudentLoan,
        //            PaymentMethod = model.PaymentMethod,
        //            UnionMember = model.UnionMember,
        //            Phone = model.Phone,
        //            Address = model.Address,
        //            City = model.City,
        //            PostCode = model.Postcode,
        //            Email = model.Email,
        //            PaymentRecordNo = model.PaymentRecordNo,
        //            FullName = model.FullName
        //        };
        //        if (model.ImageUrl != null & model.ImageUrl.Length > 0)
        //        {
        //            var uploadDir = @"images/PaymentRecords";
        //            var filename = Path.GetFileNameWithoutExtension(model.ImageUrl.FileName);
        //            var extension = Path.GetExtension(model.ImageUrl.FileName);
        //            var webrootPath = _webHostEnvironment.WebRootPath;
        //            filename = DateTime.UtcNow.ToString("yymmssfff") + filename + extension;
        //            var path = Path.Combine(webrootPath, uploadDir, filename);
        //            await model.ImageUrl.CopyToAsync(new FileStream(path, FileMode.Create));
        //            PaymentRecord.ImageUrl = "/" + uploadDir + "/" + filename;

        //        }
        //        await _PaymentRecordService.UpdateAsync(PaymentRecord);
        //        return RedirectToAction("Index");
        //    }
        //    return View();
        //}
        //[HttpGet]
        //public IActionResult Delete(int id)
        //{
        //    var PaymentRecord = _PaymentRecordService.GetById(id);
        //    if (PaymentRecord == null)
        //    {
        //        return NotFound();
        //    }
        //    var model = new PaymentRecordDeleteViewModel
        //    {
        //        Id = PaymentRecord.Id,
        //        FullName = PaymentRecord.FullName
        //    };
        //    return View(model);
        //}
        //[HttpPost]
        //public async Task<IActionResult> Delete(PaymentRecordDeleteViewModel model)
        //{
        //    await _PaymentRecordService.Delete(model.Id);
        //    return RedirectToAction("Index");
        //}
    }
}

pay1193/Pay1193/Views/PaymentRecord/Create.cshtml
@using System.Diagnostics
@using System.Globalization
@model PaymentRecordCreateViewModel

<div class="col-md-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a asp-controller="PaymentRecord" asp-action="Index">Payment Record List</a>
                    </li>
                    <li class="breadcrumb-item active" aria-current="page">New Payment Record</li>
                </ol>
            </nav><br />
            <form method="post" asp-action="Create" enctype="multipart/form-data">
                
                <div class="form-group">
                    <label>Full Name</label>
                    <select asp-for="EmployeeId" class="form-control">
                       
                        @foreach(var item in ViewBag.employees)
                        {
                            <option value="@item.Id">@item.FullName</option>
                           
                        }
                       
                    </select>                  
                </div>

                <div class="form-row">

                    <div class="form-group col-md-1">
                        <label asp-for="MonthPay"></label>
                    </div>
                    <div class="form-group col-md-3">
                        <select asp-for="MonthPay" class="form-control">
                            @{
                                var monthName = DateTimeFormatInfo.CurrentInfo.MonthNames;
                                

                               for (int i = 0; i < monthName.Length - 1; i++)
                                {
                                    var date = new DateTime(DateTime.Now.Year, i + 1, DateTime.Now.Day);
                                    <option value="@date">@monthName[i]</option>
                                }
                            }
                        </select>
                        <span asp-validation-for="MonthPay" class="text-danger"></span>
                    </div>



                    <div class="form-group col-md-1">
                        <label>Tax Year</label>
                    </div>
                    <div class="form-group col-md-3">
                        <select asp-for="TaxYearId" class="form-control">
                            @foreach(var item in ViewBag.taxYears)
                            {
                                <option value = "@item.Id">@item.YearOfTax</option>
                            }
                        </select>
                        <span asp-validation-for="TaxYearId" class="text-danger"></span>
                    </div>



                    <div class="form-group col-md-1">
                        <label asp-for="DatePay"></label>
                    </div>
                    <div class="form-group col-md-3">
                        <input type="date" class="form-control" asp-for="DatePay" />
                        <span asp-validation-for="DatePay" class="text-danger"></span>
                    </div>



                    <div class="form-group col-md-1">
                        <label asp-for="HourlyRate"></label>
                    </div>
                    <div class="form-group col-md-3">
                        <input type="text" class="form-control" asp-for="HourlyRate" placeholder="0.00"/>
                        <span asp-validation-for="HourlyRate" class="text-danger"></span>
                    </div>



                    
                    <div class="form-group col-md-1">
                        <label asp-for="HourWorked"></label>
                    </div>
                    <div class="form-group col-md-3">
                        <input type="text" class="form-control" asp-for="HourWorked" placeholder="0.00"/>
                        <span asp-validation-for="HourWorked" class="text-danger"></span>
                    </div>



                    <div class="form-group col-md-1">
                        <label asp-for="ContractualHours"></label>
                    </div>
                    <div class="form-group col-md-3">
                        <input type="text" class="form-control" asp-for="ContractualHours" placeholder="0.00" />
                        <span asp-validation-for="ContractualHours" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group">
                    <button type="submit" class="btn btn-secondary btn-rounded float-left" style="margin-right:auto.7em">Compute & Save</button>
                    <a asp-controller="PaymentRecord" asp-action="Index" class="btn btn-primary btn-rounded float-right" style="margin-right:auto.7em">Back to Pay List</a>
                    <br />
                    <br />
                </div>

            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_validationScriptsPartial");
    }
    }

pay1193/Pay1193/Views/PaymentRecord/Index.cshtml
@model IEnumerable<PaymentRecordIndexViewModel>

@{
    ViewBag.Title = "Payment Record";
}
<div class="row">
    <div class="card">
        <div class="card-body">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="breadcrumb-item active" aria-current="page">Employee List</li>
                </ol>
            </nav><br />
            <div class="row">
                <a class="btn btn-xs btn-outline-success float-md-right"
                   asp-controller="PaymentRecord" asp-action="Create">Create Payment Record</a>
                <table class="table table-striped table-dark">
                    <thead>
                        <tr>
                            <th>Employee</th>
                            <th>Pay Date</th>
                            <th>Month</th>
                            <th>Tax Year</th>
                            <th>Total Earnings</th>
                            <th>Total Deductions</th>
                            <th>Net Pay</th>
                            <th class="text-warning">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>

                                <td>
                                    <a>@item.FullName</a>
                                </td>
                                <td>
                                    <a>@item.DatePay</a>
                                </td>
                                <td>
                                    <a>@item.MonthPay</a>
                                </td>
                                <td>
                                    <a>@item.TaxYear</a>
                                </td>
                                <td>
                                    <a>@item.TotalEarnings</a>
                                </td>
                                <td>
                                    <a>@item.EarningDeduction</a>
                                </td>
                                <td>
                                    <a>@item.NetPayment</a>
                                </td>
                                <td>
                                    <a class="text-primary"
                                   asp-controller="PaymentRecord"
                                   asp-action=""
                                   asp-route-id=""><i class="fas fa-bars"></i>Preview Payslip</a>

                                    <a class="text-danger"
                                   asp-controller="PaymentRecord"
                                   asp-action=""
                                   asp-route-id=""><i class="fas fa-file-alt"></i>Payslip PDF</a>
                                </td>

                            </tr>
                        }
                    </tbody>
                </table>
            </div>

        </div>
    </div>
</div>